#!/usr/bin/env python3
"""Generate recipe HTML files and update index.html from recipe data."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = {
    "bolos": "Bolos",
    "doces": "Doces",
    "salgados": "Salgados",
    "massas": "Massas",
    "carnes": "Carnes",
    "aves": "Aves",
    "frutos-do-mar": "Frutos do mar",
    "sopas": "Sopas",
    "acompanhamentos": "Acompanhamentos",
    "bebidas": "Bebidas",
    "outros": "Outros",
}

# Every new recipe from this pending batch (not already in the book).
RECIPES: list[dict] = [
    # --- UG cookies ---
    {
        "cat": "doces",
        "slug": "biscoitos-de-chocolate",
        "title": "Biscoitos de chocolate",
        "meta": None,
        "ingredients": [
            "1 xícara de margarina",
            "4 colheres de açúcar",
            "1 e ½ xícaras de farinha de trigo",
            "2 colheres de maizena",
            "3 colheres de chocolate em pó",
        ],
        "steps": [
            "Na tigela, misture a margarina e o açúcar.",
            "Junte os demais ingredientes e misture bem com as mãos.",
            "Faça bolinhas achatadas e coloque em assadeiras sem untar.",
            "Se desejar, use um carimbo de biscoitos para decorar.",
            "Asse por 20 minutos.",
        ],
        "notes": "Receita do kit Carimbo UG; o carimbo é opcional.",
    },
    {
        "cat": "doces",
        "slug": "biscoitos-de-maracuja",
        "title": "Biscoitos de maracujá",
        "meta": None,
        "ingredients": [
            "125 g de manteiga em temperatura ambiente",
            "1 xícara de farinha de trigo peneirada",
            "¼ de xícara de açúcar de confeiteiro peneirado",
            "⅓ xícara de amido de milho (maizena)",
            "40 ml de suco de maracujá",
        ],
        "steps": [
            "Em uma tigela, misture todos os ingredientes até a massa desgrudar da mão. Se necessário, adicione um pouco mais de farinha.",
            "Faça pequenas bolinhas.",
            "Se desejar, decore com carimbo de biscoitos.",
            "Leve ao forno em tabuleiro untado por aproximadamente 30 min em fogo baixo.",
        ],
        "notes": "Receita do kit Carimbo UG.",
    },
    {
        "cat": "doces",
        "slug": "biscoitos-amanteigados-de-laranja",
        "title": "Biscoitos amanteigados de laranja",
        "meta": None,
        "ingredients": [
            "200 g de manteiga em temperatura ambiente",
            "2 xícaras (chá) de açúcar",
            "4 xícaras (chá) de farinha de trigo",
            "½ colher (café) de cravo em pó",
            "Raspas de 2 laranjas",
        ],
        "steps": [
            "Misture os ingredientes e amasse até se soltar das mãos.",
            "Modele os biscoitos a gosto e disponha em assadeira forrada com papel-manteiga.",
            "Se desejar, decore com carimbo de biscoitos.",
            "Leve ao forno médio preaquecido (200 °C) por cerca de 20 minutos ou até dourar; deixe esfriar.",
        ],
    },
    {
        "cat": "doces",
        "slug": "biscoitos-de-nata",
        "title": "Biscoitos de nata",
        "meta": None,
        "ingredients": [
            "2 colheres (sopa) de margarina",
            "10 colheres (sopa) de açúcar",
            "1 pitada de sal",
            "1 xícara (chá) de nata",
            "1 colher (chá) de fermento em pó",
            "Farinha de trigo até dar o ponto",
        ],
        "steps": [
            "Misture todos os ingredientes até desgrudar das mãos.",
            "Faça bolinhas médias.",
            "Se desejar, decore com carimbo de biscoitos.",
            "Unte uma forma, disponha os biscoitos e asse em forno preaquecido a 180 °C até dourar.",
        ],
    },
    {
        "cat": "doces",
        "slug": "biscoitos-de-limao",
        "title": "Biscoitos de limão",
        "meta": None,
        "ingredients": [
            "4 colheres (sopa) de manteiga",
            "½ xícara (chá) de açúcar",
            "2 e ½ xícaras (chá) de farinha de trigo",
            "1 ovo",
            "5 colheres (sopa) de suco de limão",
            "1 colher (chá) de fermento em pó",
        ],
        "steps": [
            "Bata a manteiga com o açúcar até ficar cremoso. Junte os demais ingredientes e misture até obter massa macia. Envolva em plástico e leve à geladeira por ½ hora.",
            "Abra a massa até cerca de 4 mm e corte os biscoitos.",
            "Se desejar, decore com carimbo.",
            "Coloque em assadeira com papel-manteiga e asse em forno médio preaquecido (180 °C) por 20 minutos ou até dourar.",
        ],
    },
    {
        "cat": "doces",
        "slug": "biscoitos-amanteigados",
        "title": "Biscoitos amanteigados",
        "meta": None,
        "ingredients": [
            "100 g de manteiga",
            "100 g de açúcar fino",
            "300 g de farinha de trigo",
            "1 ovo",
            "1 colher (sobremesa) de fermento",
        ],
        "steps": [
            "Em uma tigela, misture todos os ingredientes.",
            "Amasse até ficar homogênea; abra a massa e leve ao congelador por 30 minutos.",
            "Corte os biscoitos; se desejar, estampe com carimbo.",
            "Pré-aqueça o forno a 180 °C e asse por 15 minutos.",
        ],
    },
    # --- Malu musses ---
    {
        "cat": "doces",
        "slug": "musse-de-guarana",
        "title": "Musse de guaraná",
        "meta": [("Rendimento", "4 porções"), ("Tempo", "50 min + 2 h geladeira")],
        "ingredients": [
            "1 envelope de gelatina em pó sem sabor",
            "1 litro de refrigerante de guaraná",
            "1 xícara (chá) de açúcar",
            "1 lata de creme de leite",
        ],
        "steps": [
            "Polvilhe a gelatina sobre ½ xícara (chá) do guaraná e deixe descansar 5 minutos. Dissolva em banho-maria.",
            "No liquidificador, bata a gelatina com 1½ xícara do guaraná, ½ xícara do açúcar e o creme de leite. Distribua em taças e leve à geladeira por 2 horas.",
            "Leve o restante do guaraná e do açúcar ao fogo por 20 minutos até virar calda. Despeje sobre a musse e sirva.",
        ],
        "notes": "Fonte: Malu Receitas Mini.",
    },
    {
        "cat": "doces",
        "slug": "musse-requintada",
        "title": "Musse requintada",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 caixa de gelatina em pó sabor frutas vermelhas",
            "⅓ xícara (chá) de água quente",
            "250 g de cream cheese",
            "1 pote de iogurte natural (200 g)",
            "3 claras",
            "3 colheres (sopa) de açúcar",
            "½ xícara (chá) de geleia sabor frutas vermelhas",
        ],
        "steps": [
            "Dissolva a gelatina na água quente e deixe esfriar. Bata no liquidificador com o cream cheese e o iogurte.",
            "Bata as claras em neve, acrescente o açúcar até formar suspiro e misture ao creme.",
            "Decore as laterais das taças com a geleia levemente aquecida, distribua a musse e leve à geladeira por 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-napolitana",
        "title": "Musse napolitana",
        "meta": [("Rendimento", "8 porções"), ("Tempo", "1 h + ~2 h 20 geladeira")],
        "ingredients": [
            "1 envelope de gelatina em pó sem sabor",
            "⅓ xícara (chá) de água",
            "1 xícara (chá) de sorvete sabor creme amolecido",
            "1 lata de leite condensado",
            "1 lata de creme de leite",
            "1 colher (sopa) de essência de baunilha",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "3 colheres (sopa) de mistura para leite sabor morango",
            "100 g de chocolate meio amargo derretido",
        ],
        "steps": [
            "Hidrate a gelatina na água 5 minutos e dissolva em banho-maria. Bata com o sorvete, o leite condensado, o creme de leite e a baunilha.",
            "Bata as claras em neve com o açúcar até suspiro e misture ao creme. Divida em três partes.",
            "Distribua a primeira (baunilha) em taças e gele 20 minutos. Misture a segunda com o pó de morango e despeje. A terceira com o chocolate derretido. Gele mais 2 horas.",
        ],
        "notes": "Receita da capa da revista Malu; pode servir com cobertura de chocolate.",
    },
    {
        "cat": "doces",
        "slug": "musse-de-coco-com-calda-de-pessego",
        "title": "Musse de coco com calda de pêssego",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 caixa de maria-mole em pó sabor coco",
            "5 colheres (sopa) de água quente",
            "1 xícara (chá) de sorvete sabor coco amolecido",
            "1 lata de creme de leite gelado sem soro",
            "2 claras",
            "1 colher (chá) de essência de baunilha",
            "6 metades de pêssego em calda (reserve o xarope)",
        ],
        "steps": [
            "Dissolva a maria-mole na água quente e bata com o sorvete e o creme de leite.",
            "Bata as claras em neve e misture delicadamente. Despeje em forma de aro (20 cm) umedecida e gele 4 horas.",
            "Bata a baunilha, os pêssegos e ½ xícara do xarope. Desenforme a musse, cubra com a calda e sirva.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-baunilha-e-compota-de-uva",
        "title": "Musse de baunilha e compota de uva",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 envelope de gelatina sem sabor",
            "4 colheres (sopa) de água",
            "1 pote de iogurte natural (200 g)",
            "1 lata de leite condensado",
            "1 colher (chá) de essência de baunilha",
            "2 claras",
            "3 colheres (sopa) de açúcar",
            "⅓ xícara (chá) de açúcar (calda)",
            "1 xícara (chá) de suco de uva concentrado",
            "1 xícara (chá) de uvas verdes sem semente cortadas ao meio",
        ],
        "steps": [
            "Hidrate a gelatina na água 5 minutos e dissolva em banho-maria. Bata com o iogurte, o leite condensado e a baunilha.",
            "Bata as claras em neve com o açúcar até suspiro e misture ao creme. Distribua em taças e gele 4 horas.",
            "Para a calda: dissolva o açúcar no suco e cozinhe 6 minutos em fogo baixo. Junte as uvas até formar calda não muito grossa. Esfrie e sirva sobre a musse.",
        ],
        "notes": "Final da calda completado com o trecho da página seguinte do mesmo livreto.",
    },
    {
        "cat": "doces",
        "slug": "musse-espuma-de-pessego",
        "title": "Musse espuma de pêssego",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "50 min + 4 h geladeira")],
        "ingredients": [
            "1 lata de pêssegos em calda (reserve o xarope)",
            "1 lata de creme de leite gelado sem soro",
            "2 claras",
            "1 colher (sopa) de açúcar",
            "1 xícara (chá) de suspiros esfarelados grosseiramente",
        ],
        "steps": [
            "Bata os pêssegos, 4 colheres do xarope e o creme de leite até homogenizar.",
            "Bata as claras em neve com o açúcar até suspiro e misture ao creme. Distribua em taças e gele 4 horas.",
            "Polvilhe os suspiros na hora de servir.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-delicia",
        "title": "Musse delícia",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "1 h + 4 h geladeira")],
        "ingredients": [
            "Camada escura: 1 colher (sopa) de maisena, 2 xícaras (chá) de leite, 3 colheres (sopa) de açúcar, 250 g de chocolate meio amargo picado, 2 claras",
            "Camada branca: 1 colher (sopa) de maisena, 2 xícaras (chá) de leite, 250 g de chocolate branco picado, 1 colher (sopa) de açúcar, raspas de 1 limão, 2 claras",
            "Raspas de chocolate para decorar",
        ],
        "steps": [
            "Em fogo baixo, misture a maisena diluída no leite, o açúcar e o chocolate meio amargo por 5 minutos. Esfrie, junte as claras em neve e despeje nas taças.",
            "Repita com chocolate branco, açúcar e maisena; acrescente as raspas de limão e as claras em neve. Esfrie e despeje sobre a camada escura.",
            "Gele 4 horas, decore com raspas e sirva.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-festa",
        "title": "Musse de festa",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 caixa de gelatina em pó sabor laranja",
            "5 colheres (sopa) de água quente",
            "2 colheres (sopa) de mel",
            "1 xícara (chá) de ricota amassada",
            "1 lata de creme de leite",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "½ xícara (chá) de frutas cristalizadas",
            "4 colheres (sopa) de castanha-do-pará torrada e picada",
            "Fatias de laranja para decorar",
        ],
        "steps": [
            "Dissolva a gelatina na água quente e bata com o mel, a ricota e o creme de leite.",
            "Bata as claras em neve com o açúcar até suspiro e misture. Junte as frutas e as castanhas.",
            "Despeje em forma forrada com filme, gele 4 horas, desenforme e decore com laranja.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-caramelada-de-banana-e-gengibre",
        "title": "Musse caramelada de banana e gengibre",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "50 min + 4 h geladeira")],
        "ingredients": [
            "1 envelope de gelatina sem sabor",
            "7 colheres (sopa) de água",
            "½ xícara (chá) de açúcar",
            "2 colheres (sopa) de gengibre picado",
            "3 bananas-nanicas maduras picadas",
            "Suco de 1 limão",
            "1 lata de creme de leite",
        ],
        "steps": [
            "Hidrate a gelatina em 4 colheres de água e dissolva em banho-maria.",
            "Dissolva o açúcar nas 3 colheres de água restantes com o gengibre; cozinhe 12 minutos até calda caramelada.",
            "Bata a gelatina, a banana, o limão e o creme de leite. Distribua em taças, gele 4 horas e sirva com a calda fria.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-paixao",
        "title": "Musse Paixão",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "½ xícara (chá) de polpa de maracujá",
            "4 colheres (sopa) de açúcar",
            "4 colheres (sopa) de água",
            "3 ovos (claras e gemas separadas)",
            "300 g de chocolate ao leite derretido",
            "1 lata de creme de leite",
            "1 pacote de biscoito champanhe (180 g)",
        ],
        "steps": [
            "Ferva a polpa com metade do açúcar e a água por 10 minutos até calda; esfrie.",
            "Bata as gemas com o restante do açúcar por 7 minutos. Misture o chocolate e o creme de leite; incorpore as claras em neve.",
            "Forre o fundo das taças com biscoitos e um pouco de calda, cubra com o creme, decore com a calda restante e gele 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-morango",
        "title": "Musse de morango",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "40 min + 4 h geladeira")],
        "ingredients": [
            "1 caixa de gelatina em pó sabor morango",
            "½ xícara (chá) de água quente",
            "1 xícara (chá) de morango picado",
            "1 lata de creme de leite gelado sem soro",
            "150 g de cream cheese",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "½ pacote de biscoito champanhe quebrado (90 g)",
            "6 morangos para decorar",
            "Calda: ½ xícara (chá) de geleia de morango + 2 colheres (sopa) de água",
        ],
        "steps": [
            "Dissolva a gelatina na água quente e bata com os morangos, o creme de leite e o cream cheese.",
            "Bata as claras em neve com o açúcar até suspiro e misture ao creme.",
            "Forre as taças com os biscoitos, cubra com o creme e gele 4 horas. Cozinhe a geleia com a água 3 minutos, esfrie, espalhe e decore com morangos.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-chic",
        "title": "Musse chic",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "40 min + 4 h geladeira")],
        "ingredients": [
            "4 peras descascadas, sem sementes e picadas",
            "½ xícara (chá) + 4 colheres (sopa) de água",
            "3 colheres (sopa) de açúcar",
            "1 envelope de gelatina sem sabor",
            "2 xícaras (chá) de creme de leite fresco",
            "½ pacote de biscoito champanhe quebrado (90 g)",
            "100 g de chocolate meio amargo picado",
            "Raspas de chocolate para decorar",
        ],
        "steps": [
            "Cozinhe as peras com ½ xícara de água e o açúcar por 8 minutos; esfrie.",
            "Hidrate a gelatina nas 4 colheres de água e dissolva em banho-maria. Bata com as peras e o creme de leite. Misture biscoitos e chocolate.",
            "Distribua em taças, gele 4 horas e decore com raspas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-tangerina-e-chocolate-branco",
        "title": "Musse de tangerina e chocolate branco",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "50 min + 4 h geladeira")],
        "ingredients": [
            "200 g de chocolate branco derretido",
            "1 lata de creme de leite gelado sem soro",
            "1 envelope de gelatina sem sabor",
            "½ xícara (chá) de suco concentrado de tangerina",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "Raspas de 1 tangerina",
        ],
        "steps": [
            "Misture o chocolate e o creme de leite.",
            "Hidrate a gelatina no suco 5 minutos e dissolva em banho-maria; junte ao creme.",
            "Bata as claras em neve com o açúcar até suspiro, misture, distribua em taças, gele 4 horas e polvilhe as raspas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-manga-com-leite-de-coco",
        "title": "Musse de manga com leite de coco",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 envelope de gelatina sem sabor",
            "1 garrafinha de leite de coco (200 ml)",
            "2 xícaras (chá) de manga em cubos",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "Folhas de hortelã para decorar",
        ],
        "steps": [
            "Hidrate a gelatina no leite de coco 5 minutos e dissolva em banho-maria. Bata com a manga.",
            "Bata as claras em neve com o açúcar até suspiro e misture ao creme.",
            "Distribua em taças, gele 4 horas e decore com hortelã.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-maracuja",
        "title": "Musse de maracujá",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "Polpa de 4 maracujás",
            "½ xícara (chá) + 4 colheres (sopa) de água",
            "½ xícara (chá) + 2 colheres (sopa) de açúcar",
            "1 envelope de gelatina sem sabor",
            "1 xícara (chá) de ricota amassada",
            "1 caixa de creme de leite (200 g)",
            "2 claras",
        ],
        "steps": [
            "Ferva a polpa com ½ xícara de água e ½ xícara de açúcar por 10 minutos; esfrie.",
            "Hidrate a gelatina nas 4 colheres de água e dissolva em banho-maria. Bata com a ricota e o creme de leite.",
            "Bata as claras em neve com o restante do açúcar. Misture metade da calda ao creme e às claras; despeje em taças, gele 4 horas e sirva com o restante da calda.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-abobora-com-amendoim",
        "title": "Musse de abóbora com amendoim",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1½ xícara (chá) de creme de leite fresco gelado",
            "2 colheres (sopa) de açúcar",
            "1½ xícara (chá) de doce de abóbora em pasta",
            "Calda: 2 colheres (sopa) de manteiga, ½ xícara (chá) de amendoim sem casca, ½ xícara (chá) de açúcar mascavo, 1 caixa de creme de leite (200 g)",
        ],
        "steps": [
            "Para a calda: derreta a manteiga, frite o amendoim 3 minutos, junte o açúcar mascavo 3 minutos e o creme de leite por 5 minutos. Esfrie.",
            "Bata o creme fresco até começar a engrossar, acrescente o açúcar até ponto de chantilly e misture o doce de abóbora.",
            "Distribua em taças, gele 4 horas e sirva com a calda.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-torta-de-limao",
        "title": "Musse torta de limão",
        "meta": [("Rendimento", "4 porções"), ("Tempo", "50 min + 4 h geladeira")],
        "ingredients": [
            "3 ovos",
            "⅔ xícara (chá) de açúcar",
            "⅓ xícara (chá) de suco de limão",
            "1 colher (sopa) de maisena",
            "2 colheres (sopa) de água",
            "1 lata de creme de leite gelado sem soro",
            "1 colher (sopa) de manteiga",
            "1 pacote de biscoito Maria esfarelado (200 g)",
            "Raspas de 1 limão",
        ],
        "steps": [
            "Bata os ovos e o açúcar 10 minutos. Junte o limão e a maisena diluída na água; leve ao fogo baixo até engrossar.",
            "Retire do fogo, misture o creme de leite e a manteiga.",
            "Forre as taças com metade dos biscoitos, despeje o creme, gele 4 horas e finalize com o restante dos biscoitos e as raspas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-castanha",
        "title": "Musse de castanha",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "50 min + 4 h geladeira")],
        "ingredients": [
            "1 xícara (chá) de castanha de caju",
            "1½ xícara (chá) de leite",
            "4 ovos (claras e gemas separadas)",
            "1 colher (sopa) de maisena",
            "1 lata de leite condensado",
            "Raspas de 1 laranja",
            "Castanhas para polvilhar",
        ],
        "steps": [
            "Bata as castanhas, o leite, as gemas, a maisena e o leite condensado. Cozinhe em fogo baixo até engrossar; cubra com filme e deixe esfriar.",
            "Incorpore as claras em neve. Distribua em taças, polvilhe raspas e castanhas e gele 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-biscoito-com-mel",
        "title": "Musse de biscoito com mel",
        "meta": [("Rendimento", "4 porções"), ("Tempo", "30 min + 2 h geladeira")],
        "ingredients": [
            "2 envelopes de gelatina sem sabor",
            "6 colheres (sopa) de suco de laranja",
            "1 lata de leite condensado",
            "1 lata de creme de leite gelado sem soro",
            "1 xícara (chá) de biscoito champanhe esfarelado",
            "½ xícara (chá) de mel",
            "2 colheres (sopa) de raspas de laranja",
        ],
        "steps": [
            "Hidrate a gelatina em 4 colheres do suco 5 minutos e dissolva em banho-maria. Bata com o leite condensado e o creme de leite; misture os biscoitos.",
            "Distribua em taças e gele 2 horas. Misture o mel com o suco restante e as raspas; espalhe sobre a musse.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-especial",
        "title": "Musse especial",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 xícara (chá) de amendoim torrado sem casca e triturado",
            "1½ xícara (chá) de doce de leite em pasta",
            "1½ xícara (chá) de sorvete sabor creme",
            "2 claras",
            "½ xícara (chá) de amendoim torrado picado",
            "Calda: 4 colheres (sopa) de açúcar, 80 g de chocolate meio amargo picado, 2 colheres (sopa) de água",
        ],
        "steps": [
            "Bata o amendoim triturado, o doce de leite e o sorvete. Incorpore as claras em neve. Distribua em taças e gele 4 horas.",
            "Aqueça os ingredientes da calda 5 minutos até dissolver. Esfrie, despeje sobre a musse, polvilhe o amendoim picado e sirva.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-caramelo",
        "title": "Musse caramelo",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "2 xícaras (chá) de açúcar",
            "2 xícaras (chá) de leite",
            "1 lata de creme de leite",
            "1 envelope de gelatina sem sabor",
            "3 colheres (sopa) de água",
        ],
        "steps": [
            "Derreta o açúcar até virar caramelo. Junte o leite e mexa até dissolver.",
            "Desligue o fogo, misture o creme de leite e a gelatina hidratada na água. Coloque em tigela média e gele 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-bis",
        "title": "Musse Bis",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 3 h geladeira")],
        "ingredients": [
            "1 envelope de gelatina sem sabor",
            "3 colheres (sopa) de água",
            "1 caixa de chocolate tipo Bis sabor laranja",
            "1 lata (medida) de leite",
            "1 lata de leite condensado",
            "1 lata de creme de leite",
        ],
        "steps": [
            "Hidrate a gelatina na água 5 minutos e dissolva em banho-maria.",
            "Bata todos os ingredientes no liquidificador, distribua em taças e gele 3 horas.",
        ],
        "notes": "Use a lata vazia do leite condensado para medir o leite.",
    },
    {
        "cat": "doces",
        "slug": "musse-de-amora",
        "title": "Musse de amora",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 xícara (chá) de ricota amassada",
            "1 lata de creme de leite",
            "½ xícara (chá) de geleia de amora",
            "2 claras",
            "2 colheres (sopa) de açúcar",
        ],
        "steps": [
            "Bata a ricota, o creme de leite e a geleia até homogenizar.",
            "Bata as claras em neve com o açúcar até suspiro, misture, distribua em taças e gele 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-brigadeiro-branco",
        "title": "Musse brigadeiro branco",
        "meta": [("Rendimento", "8 porções"), ("Tempo", "40 min + 2 h geladeira")],
        "ingredients": [
            "1 lata de leite condensado",
            "3 ovos",
            "1 lata de creme de leite",
            "4 colheres (sopa) de açúcar",
            "Biscoitos de chocolate para decorar",
        ],
        "steps": [
            "Leve ao fogo o leite condensado e as gemas peneiradas até desgrudar do fundo. Tire do fogo e misture o creme de leite.",
            "Bata as claras em neve com o açúcar até suspiro, misture ao creme, distribua em taças e gele 2 horas. Decore com biscoitos.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-de-amendoim",
        "title": "Musse de amendoim",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "1 h + 4 h geladeira")],
        "ingredients": [
            "1 pote de pasta de amendoim tipo Amendocrem (250 g)",
            "1 xícara (chá) de açúcar",
            "1 lata de creme de leite",
            "1 envelope de gelatina sem sabor",
            "3 colheres (sopa) de água",
            "2 claras",
            "Cobertura para sorvete sabor caramelo para decorar",
        ],
        "steps": [
            "Bata a pasta de amendoim com o açúcar até creme esbranquiçado; junte o creme de leite.",
            "Hidrate e dissolva a gelatina; bata no creme. Incorpore as claras em neve.",
            "Distribua em taças, gele 4 horas e decore com a cobertura de caramelo.",
        ],
    },
    {
        "cat": "doces",
        "slug": "musse-limonada",
        "title": "Musse limonada",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "30 min + 4 h geladeira")],
        "ingredients": [
            "1 caixa de gelatina em pó sabor limão",
            "½ xícara (chá) de água quente",
            "½ xícara (chá) de suco de limão",
            "1 xícara (chá) de gelo picado",
            "2 claras",
            "2 colheres (sopa) de açúcar",
            "Raspas da casca de 1 limão",
        ],
        "steps": [
            "Bata a gelatina dissolvida na água, o suco e o gelo no liquidificador.",
            "Bata as claras em neve com o açúcar até suspiro, misture ao creme, acrescente as raspas, distribua em taças e gele 4 horas.",
        ],
        "notes": "Para testar a neve: a clara não deve cair da colher virada.",
    },
    {
        "cat": "doces",
        "slug": "musse-bombom-de-chocolate",
        "title": "Musse bombom de chocolate",
        "meta": [("Rendimento", "6 porções"), ("Tempo", "40 min + 4 h geladeira")],
        "ingredients": [
            "1 lata de leite condensado",
            "1 colher (chá) de margarina",
            "1 colher (sopa) de maisena",
            "½ lata de leite (medida da lata do condensado)",
            "4 colheres (sopa) de chocolate em pó",
            "150 g de chocolate meio amargo picado",
            "4 bombons tipo ouro branco e preto picados",
            "1½ xícara (chá) de creme de leite fresco gelado",
        ],
        "steps": [
            "Leve ao fogo os 5 primeiros ingredientes até engrossar e desgrudar. Reserve metade; derreta o chocolate meio amargo na outra metade.",
            "Esfrie as duas misturas; junte metade dos bombons ao creme de chocolate.",
            "Bata o creme fresco em chantilly e misture ao creme sem chocolate. Monte em camadas nas taças, decore com o restante dos bombons e gele 4 horas.",
        ],
    },
    {
        "cat": "doces",
        "slug": "tortinhas-de-banana",
        "title": "Tortinhas de banana",
        "meta": [("Rendimento", "12 tortinhas")],
        "ingredients": [
            "Recheio: 3 bananas-nanicas médias, 1 colher (sopa) de suco de limão, 1 lata de Leite Moça com Chocolate, 1 colher (chá) de canela, 2 gemas, 1 colher (sopa) rasa de manteiga",
            "Massa: ¾ xícara (chá) de açúcar, 1 pitada de sal, 1 ovo, 2 xícaras (chá) de farinha de trigo, 5 colheres (sopa) de manteiga (150 g)",
        ],
        "steps": [
            "Recheio: amasse as bananas com o limão; junte ½ lata do Leite Moça e a canela; cozinhe ~15 minutos. Misture o restante do Leite Moça com as gemas e a manteiga, junte ao creme e engrosse.",
            "Massa: misture açúcar, sal e ovo; acrescente a farinha e por último a manteiga até soltar das mãos. Reserve um pedaço para decorar.",
            "Abra a massa, forre forminhas, recheie e faça xadrez com tirinhas. Asse a 180 °C até dourar. Espere esfriar bem para desenformar.",
        ],
    },
    {
        "cat": "doces",
        "slug": "flan-de-chocolate-e-creme",
        "title": "Flan de chocolate e creme",
        "meta": [("Rendimento", "6 a 8 porções")],
        "ingredients": [
            "Creme: 1 lata de Leite Moça, a mesma medida de leite, 2 gemas, 2 colheres (chá) de essência de baunilha",
            "Flan: 1 envelope de gelatina sem sabor, 4 tabletes pequenos de chocolate meio amargo (~180 g) picados, 1 lata de Leite Moça, 1 colher (chá) de raspas de laranja",
        ],
        "steps": [
            "Creme: misture tudo e cozinhe em banho-maria ~15 minutos até consistente.",
            "Flan: dissolva a gelatina conforme a embalagem. Amoleça o chocolate com 1 xícara de água em banho-maria. Misture Leite Moça, a mesma medida de água, o chocolate, a gelatina e as raspas. Despeje em taças molhadas e gele no mínimo 4 horas.",
            "Na hora de servir, despeje o creme sobre o flan.",
        ],
        "notes": "A gelatina em pó pode ser substituída por 6 folhas de gelatina branca.",
    },
    {
        "cat": "doces",
        "slug": "mousse-de-chocolate",
        "title": "Mousse de chocolate",
        "meta": None,
        "ingredients": [
            "1 barra de chocolate meio amargo",
            "4 claras em neve",
            "2 colheres (sopa) de açúcar",
            "1 lata de creme de leite sem soro",
        ],
        "steps": [
            "Coloque o creme de leite no congelador para separar bem o soro.",
            "Derreta o chocolate em banho-maria e misture o açúcar.",
            "Misture o creme de leite e depois as claras em neve, bem devagar.",
        ],
        "notes": "Receita enviada por e-mail pela Ana Paula Queiroz. Reserve 1–2 quadradinhos de chocolate para raspar por cima.",
    },
    {
        "cat": "doces",
        "slug": "sufle-de-damasco",
        "title": "Suflê de damasco",
        "meta": None,
        "ingredients": [
            "10 ovos (claras e gemas separadas)",
            "10 colheres (sopa) de açúcar (para o suflê) + 10 colheres (sopa) de açúcar (para a gemada)",
            "200 g de damasco",
            "1 colher (café) de cremor de tártaro",
            "1 lata de creme de leite",
        ],
        "steps": [
            "Cozinhe o damasco e amasse com um garfo.",
            "Bata as claras em neve, acrescente o açúcar, o damasco e o cremor de tártaro. Despeje em forma untada e enfarinhada e asse até dourar; deixe no forno desligado alguns minutos.",
            "Gemada: bata as gemas com 1 colher de açúcar cada até bem clara; misture o creme de leite. Sirva com o suflê.",
        ],
        "notes": "Pode reservar umas duas colheres de damasco amassado para a gemada. A gemada leva gemas cruas batidas com açúcar.",
    },
    {
        "cat": "doces",
        "slug": "bolinho-de-chuva",
        "title": "Bolinho de chuva",
        "meta": None,
        "ingredients": [
            "3 xícaras de farinha de trigo",
            "2 ovos",
            "1 xícara de leite",
            "1 xícara de açúcar",
            "1 pitada de sal",
            "3 colheres (chá) de fermento em pó",
            "Óleo para fritar",
            "Açúcar e canela para polvilhar",
        ],
        "steps": [
            "Misture farinha, ovos, leite, açúcar, sal e fermento até massa homogênea.",
            "Frite colheradas pequenas em óleo quente (molhe a colher no óleo para soltar a massa).",
            "Polvilhe com açúcar e canela.",
        ],
        "notes": "Fonte: ChefOnline / Marília de Melo Silveira.",
    },
    {
        "cat": "doces",
        "slug": "hang-yang-peang",
        "title": "Hang Yang Peang (bolinhas de amêndoa)",
        "meta": None,
        "ingredients": [
            "3 xícaras de farinha de trigo",
            "1 xícara de açúcar",
            "½ colher (chá) de sal",
            "½ colher (chá) de bicarbonato de sódio",
            "1 xícara de gordura em pedacinhos",
            "1 ovo inteiro (sem bater)",
            "½ colher (chá) de extrato de amêndoa",
            "Amêndoas pela metade para decorar",
        ],
        "steps": [
            "Peneire os secos. Misture a gordura até ficar farinhento. Junte o ovo e o extrato; amasse.",
            "Faça bolinhas, achate com garfo até ~1 cm e decore com amêndoa. Asse em forno moderado ~20 minutos até levemente douradas.",
        ],
        "notes": "Receita chinesa (A Cozinha Brasileira / Revista Claudia).",
    },
    {
        "cat": "doces",
        "slug": "calda-de-maracuja-para-torta",
        "title": "Calda de maracujá para torta",
        "meta": None,
        "ingredients": [
            "½ xícara (chá) de açúcar",
            "1 xícara (chá) de água quente",
            "Polpa de 3 maracujás",
        ],
        "steps": [
            "Leve o açúcar ao fogo até dourar.",
            "Acrescente a água quente e a polpa; ferva 2 minutos.",
            "Sirva quente ou fria sobre torta mousse de chocolate (ou pronta).",
        ],
        "notes": "Dica de acompanhamento para Torta Mousse Miss Daisy (Sadia). Outras dicas do mesmo folheto: decorar com morango/framboesa/hortelã; polvilhar cacau; castanhas picadas; fio de licor.",
    },
    {
        "cat": "doces",
        "slug": "morango-ao-creme",
        "title": "Morango ao creme",
        "meta": None,
        "ingredients": [
            "Morangos maduros, de tamanho uniforme",
            "1 lata de creme de leite",
            "Açúcar a gosto",
            "Opcional: 1 colher (chá) de raspas de laranja; 1–2 colheres (sopa) de licor, rum ou conhaque",
        ],
        "steps": [
            "Lave os morangos rapidamente em água fria, escorra, retire os cabinhos e arrume em taças. Mantenha refrigerados e prepare no máximo 1 hora antes.",
            "Bata levemente o creme de leite, adoce a gosto e, se quiser, junte raspas ou o licor. Sirva sobre os morangos.",
        ],
        "notes": "Fonte: Centro Nestlé de Informação ao Consumidor.",
    },
    {
        "cat": "doces",
        "slug": "torta-de-maracuja-com-ganache",
        "title": "Torta de maracujá com ganache",
        "meta": [("Rendimento", "10 porções")],
        "ingredients": [
            "Massa: 300 g de farinha, 150 g de manteiga, 150 g de açúcar, 2 ovos, baunilha a gosto",
            "Recheio: 300 g de chocolate meio amargo, 150 g de creme de leite fresco",
            "Cobertura: 1 lata de leite condensado, 150 ml de suco de maracujá concentrado",
        ],
        "steps": [
            "Misture a massa até desgrudar; forre forma desmontável e asse a 150 °C por 20 minutos.",
            "Derreta o chocolate em banho-maria, misture o creme e deixe esfriar. Espalhe sobre a massa.",
            "Misture o leite condensado com o suco e gele 1 hora. Cubra a torta. Para a teia: risque com palito do centro para fora. Sirva gelada.",
        ],
    },
    {
        "cat": "doces",
        "slug": "terrine-de-pistache",
        "title": "Terrine de pistache",
        "meta": [("Rendimento", "4 porções")],
        "ingredients": [
            "½ colher (sopa) de base para sorvete de pistache",
            "130 ml de leite",
            "100 ml de leite condensado",
            "Pistaches triturado levemente, a gosto",
            "130 ml de chantilly",
            "20 g de gelatina sem sabor",
        ],
        "steps": [
            "Dissolva a base no leite, junte o leite condensado e os pistaches; misture o chantilly com cuidado.",
            "Acrescente a gelatina hidratada e derretida em banho-maria. Despeje em forma de terrine ou torta e leve à geladeira.",
        ],
        "notes": "Sirva com calda de chocolate. Pode montar sobre pão de ló.",
    },
    {
        "cat": "doces",
        "slug": "compota-de-tomate",
        "title": "Compota de tomate",
        "meta": [("Rendimento", "8 porções")],
        "ingredients": [
            "250 ml de água",
            "60 g de gelatina de morango ou cereja",
            "140 g de açúcar",
            "2 g de cravos-da-índia",
            "½ fava de baunilha aberta",
            "1 anis-estrelado",
            "1 casca de canela",
            "700 g de tomates maduros sem pele e sem sementes",
        ],
        "steps": [
            "Ferva água, gelatina, açúcar e especiarias ~15 minutos até calda em ponto de fio fino.",
            "Junte os tomates em quartos e cozinhe ~5 minutos. Desligue, tampe e descanse 1 hora.",
            "Sirva gelada, com sorvete de especiarias.",
        ],
        "notes": "O descanso tampado deixa os tomates firmes.",
    },
    {
        "cat": "doces",
        "slug": "sorvete-de-especiarias",
        "title": "Sorvete de especiarias",
        "meta": [("Rendimento", "~25 porções (duas bolas de 60 g)")],
        "ingredients": [
            "10 g de anis-estrelado",
            "5 g de canela em pó",
            "10 g de cardamomo",
            "5 g de gengibre",
            "5 g de cravos-da-índia",
            "1 fava de baunilha aberta",
            "3 g de pimenta-branca",
            "2 l de leite",
            "50 g de base de sorvete de nata",
            "500 g de açúcar",
            "20 g de liga neutra",
        ],
        "steps": [
            "Faça um chá com as especiarias: ferva e coe.",
            "Misture leite, base, açúcar e liga neutra. Congele 6 h; bata 10 min; repita o ciclo (3 h + 10 min) mais 3 vezes até cremoso; congele 3 h.",
            "Se tiver máquina de sorvete, bata ~10 minutos e congele 3 horas.",
        ],
        "notes": "Combina com a compota de tomate. Sem base/liga neutra profissionais, use creme de leite e técnica de bater ao congelar (inferido).",
    },
]

print(f"Part 1 recipes: {len(RECIPES)}")
